const ActionTypes = {
    PERSONAL_INFORMATION:'PERSONAL_INFORMATION',
    CONTACT_INFORMATION:'CONTACT_INFORMATION',
    EDUCATIO_INFORMATION:'EDUCATION_INFORMATION',
    QUALIFICATION_INFORMATION:'QUALIFICATION_INFORMATION',
    PEROSONAL_INFORMATION_SUCCESS:'PERSONAL_INFORMATION_SUCCESS',
    REFERENCES_INFORMATION:'REFERENCES_INFORMATION',
    SKILL_INFORMATION:'SKILL_INFORMATION',
    WORK_INFORMATION:'WORK_INFORMATION'
}

export default ActionTypes

